include:
  - template: Terraform/Base.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml   # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/SAST-IaC.gitlab-ci.yml

stages:
  - test
  - packer
  - terraform

test:cargo:
  stage: test
  image: "rust:latest"
  tags:
    - rust
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose

packer:
  stage: packer
  needs: ["test:cargo"]
  only:
    - tags
    - main
  tags:
    - shell
  script:
    - packer build packer/packer.json 

terraform:fmt:
  stage: terraform
  needs: ["packer"]
  extends: .terraform:fmt
  tags:
    - shell
terraform:validate:
  stage: terraform
  extends: .terraform:validate
  tags:
    - shell
terraform:build:
  stage: terraform
  extends: .terraform:build
  tags:
    - shell
terraform:deploy:
  stage: terraform
  extends: .terraform:deploy
  dependencies:
    - terraform:build
  variables:
    TF_VAR_pm_api_url: ${PROXMOX_URL}
    TF_VAR_pm_api_token_id: ${PROXMOX_USERNAME}
    TF_VAR_pm_api_token_secret: ${PROXMOX_TOKEN}
    TF_VAR_ssh_key: ${SSH_KEY}
  tags:
    - shell