stages:
  - test
  - packer
  - terraform

image: "rust:latest"

test:cargo:
  stage: test
  tags:
    - rust
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose

packer:
  stage: packer
  tags:
    - shell
  script:
    - packer build infra/packer.json 

terraform:init:
  stage: terraform
  tags:
    - shell
  script:
    - terraform init
    - terraform plan

terraform:apply:
  stage: terraform
  tags:
    - shell
  script:
    - terraform apply -auto-approve
