stages:
  - terraform
terraform:
  stage: terraform
  variables:
    TF_VAR_pm_api_url: ${PROXMOX_URL}
    TF_VAR_pm_api_token_id: ${PROXMOX_USERNAME}
    TF_VAR_pm_api_token_secret: ${PROXMOX_TOKEN}
    TF_VAR_ssh_key: ${SSH_KEY}
  tags:
    - shell
  script:
    - terraform -chdir=terraform init
    - terraform -chdir=terraform plan
    - terraform -chdir=terraform apply -auto-approve
