stages:
  - test
  - packer
  - terraform

test:cargo:
  stage: test
  image: "rust:latest"
  tags:
    - rust
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose

packer:
  stage: packer
  only:
    - tags
    - main
  tags:
    - shell
  script:
    - packer build packer/packer.json 

terraform:
  stage: terraform
  only:
    - tags
    - main
  variables:
    TF_VAR_pm_api_url: ${PROXMOX_URL}
    TF_VAR_pm_api_token_id: ${PROXMOX_USERNAME}
    TF_VAR_pm_api_token_secret: ${PROXMOX_TOKEN}
    TF_VAR_ssh_key: ${SSH_KEY}
  tags:
    - shell
  script:
    - terraform -chdir=terraform init
    - terraform -chdir=terraform plan
    - terraform -chdir=terraform apply -auto-approve
