stages:
  - test
  - packer
  - terraform

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cargo/bin
    - .cargo/registry/index
    - .cargo/registry/cache
    - target/debug/deps
    - target/debug/build
  policy: pull-push

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

test:cargo:
  stage: test
  image: "rust:1.75.0"
  tags:
    - rust
  script:
    - rustc --version && cargo --version
    - cargo test --workspace --verbose

packer:
  stage: packer
  needs: ["test:cargo"]
  only:
    - tags
    # - main
  tags:
    - shell
  script:
    - packer init -upgrade packer
    - packer build -debug packer
  cache:
    <<: *global_cache
    policy: pull 

terraform:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  stage: terraform
  needs: ["packer"]
  before_script:
    - cd ${TF_ROOT}
  cache:
    key: example-production
    paths:
      - ${TF_ROOT}/.terraform
  only:
    - tags
    # - main
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/terraform
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/tugstate
    TF_VAR_pm_api_url: ${PROXMOX_URL}
    TF_VAR_pm_api_token_id: ${PROXMOX_USERNAME}
    TF_VAR_pm_api_token_secret: ${PROXMOX_TOKEN}
    TF_VAR_ssh_key: ${SSH_KEY}
    TF_VAR_tag_version: ${CI_COMMIT_TAG}
  tags:
    - terraform
  script:
    - gitlab-terraform init
    - gitlab-terraform plan
    - gitlab-terraform apply
