stages:
  - terraform
terraform:
  stage: terraform
  tags:
    - shell
  script:
    - terraform -chdir=terraform init
    - terraform -chdir=terraform plan
    - terraform -chdir=terraform apply -auto-approve
