stages:
  - test
  - packer
  - terraform

test:cargo:
  stage: test
  image: "rust:latest"
  tags:
    - rust
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose

packer:
  stage: packer
  needs: ["test:cargo"]
  only:
    - tags
    - main
  tags:
    - shell
  script:
    - packer init -upgrade packer/packer.pkr.hcl
    - packer build -debug packer/packer.pkr.hcl 

terraform:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  stage: terraform
  needs: ["packer"]
  before_script:
    - cd ${TF_ROOT}
  cache:
    key: example-production
    paths:
    - ${TF_ROOT}/.terraform
  only:
    - tags
    - main
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/terraform
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/tugstate
    TF_VAR_pm_api_url: ${PROXMOX_URL}
    TF_VAR_pm_api_token_id: ${PROXMOX_USERNAME}
    TF_VAR_pm_api_token_secret: ${PROXMOX_TOKEN}
    TF_VAR_ssh_key: ${SSH_KEY}
  tags:
    - terraform
  script:
    - gitlab-terraform init
    - gitlab-terraform plan
    - gitlab-terraform apply
