stages:
  - terraform

image: "rust:latest"

test:cargo:
  stage: test
  tags:
    - rust
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose

packer:
  stage: packer
  tags:
    - shell
  script:
    - packer build packer/packer.json 

terraform:
  stage: terraform
  tags:
    - shell
  script:
    - terraform -chdir=terraform init
    - terraform -chdir=terraform plan
    - terraform -chdir=terraform apply -auto-approve
