// pub mod elkmen;
pub mod bsky;
pub mod derpies;
pub mod elon;
pub mod eventhandler;
pub mod feat;
pub mod gulag;
pub mod horny;
pub mod instagram;
pub mod nickname;
pub mod phony;
pub mod teh;
pub mod tiktok;
pub mod twitter;
